# 203443601 203392964
# Cohenoh2 kleinid1

bin:
	mkdir bin
compile: bin
	javac -d bin -cp biuoop-1.4.jar src/*/*.java src/*.java
jar:
	jar cfm ass6game.jar Manifest.mf -C bin . -C resources . 
run:
	java -jar ass6game.jar
check:
	java -jar checkstyle-5.7-all.jar -c biuoop.xml src/*/*.java src/*.java